### PR TITLE
Wrote GET APIs & database using SQLs& python && Built up on AWS

### PR DESCRIPTION
**Pull request by steward379**
Server Running on the given public IPV4 IP on Unix
- wrote App.py API GET using python3, mysqlconnector
- build up MySQL database with python
- Setup EC2 Instance Unix environment

### CODE REVIEW

**Comment by cwpeng** [comment]
Leave your testing URLs so that I can test for you.

**Comment by steward379** [comment]
Hosting at: 
http://54.253.20.174:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Two small issues:
1. `Category` field should be `category`.
2. Endpoint of single attraction API is `/api/attraction/<attraction_id>`

Re-request review after you fixed them.

**Comment by steward379** [comment]
Thanks, All the bugs shall be fixed by now.

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by steward379** [comment]
Thanks for all the help 🫡

**Pull request merged**
