### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by steward379**
- [CSS} wrote base.css for universal styles
- [JS] make man-made swiper by vanilla javaScript using multiple tools
- [CSS] make the style looks similar to that of Figma's

http://54.253.20.174:3000/
http://54.253.20.174:3000/attraction/1

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1, Separating lines are 1px height only.
2. There is no space between navigator bar and image slider in mobile layout.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Top separating line is still 2px height.

**Comment by steward379** [comment]
Please kindly check it out again.
[CSS][SCSS] I also put different CSS styles in files.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
